

indexing-settings:
  maxFrequency: 1000 #макс кол страниц с данной леммой (отсев самых частых)
  deepLimit: 2 #глубина поиска подстраниц/ уровень главной страницы=1, без ограничений=0
  offset: 10 #размер порциирезультатов поиска
  limit: 50 #макс кол результатов поиска которые нужно вывести
  userAgent: LocalSearchBot #Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referer: http://www.google.
  responseWait : 10000 #ожидание ответа в мс
  timeout: 1000 #таймаут между обращениями к сайт
  readSubDomain: false #обрабатывать ли поддомены //ЭТО ВООБЩЕ НЕЛЬЗЯ, НЕ УКЛАДЫВАЕТСЯ В ЗАДВНИЕ, поэтому пофиксить и убрать этот переключатель нафиг
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
#    - url: https://mail.ru/
#      name: mailRu
  redissonHost: redis://127.0.0.1:6379 #расположение сервера Redis
server:
  port: 8085

spring:
  datasource:
#    username: root
#    password: pass
#    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=false
#    url: jdbc:mysql://localhost:3306/search_engine
    url: jdbc:postgresql://localhost:5433/postgres
    username: root
    password: pass
    jpa:
      show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled : true #версифицирование отключено
  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto:  none #validate #update #drop #create-only #create #create-drop
      show_sql: true
      format_sql: true
      type: trace
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE




