# example values

indexing-settings:
  testQq: 7
  deepLimit : 2 #глубина поиска подстраниц/ уровень главной страницы=1
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru

server:
  port: 8085

spring:
  datasource:
#    username: root
#    password: pass
#    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=false
#    url: jdbc:mysql://localhost:3306/search_engine
    url: jdbc:postgresql://localhost:5433/postgres
    username: root
    password: pass
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled : true #версифицирование отключено
  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto:  none #validate #update #drop #create-only #create #create-drop
    show-sql: true



